[project]
name = "production-rag-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.7",
    "fastapi>=0.127.0",
    "sentence-transformers>=5.2.0",
    "uvicorn>=0.40.0",
]
